# Generated by Django 4.2 on 2023-04-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("node_name", models.CharField(max_length=250)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("data_type", models.CharField(max_length=100)),
                ("data_value", models.FloatField()),
            ],
        ),
    ]
